module.exports={
    UNAUTHORIZED:"UNAUTHORIZED",
    CREATED:"Created",
    SUCCESS:"Success",
    LOGIN:"login",
    REGISTER:"Registered",
    INVALID_EMAIL:"Invalid Email",
    INVALID_PASSWORD:"Invalid Password",
    INACTIVE:"Your profile is not Active",
    USER_LIST:"User Fetched",
    NOT_ALLOWED:"Only Admin can access",
    USER_VERIFIED:"User Verified",
    ALREDY_VERIFIED:"Already Verified",
    POST_CREATED:"Post Created",
    USER_DELETED:"user Deleted",
    TRY_AGAIN:"Try Again",
    POST_DELETED:"Post Deleted",
    POST_UPDATED:"Post Updated",
    ALL_POST:"All Post list",
    CANNOT_EDIT_POST:"Not Allowed to Edit Other Author's Post",
    CANNOT_DELETE_POST:"Not Allowed to Delete Other Author's Post",
    COMMENT_CREATED:"Comment Created",
    INVALID_POSTID:"Invalid Post Id",
    COMMENT_UPDATED:"Comment Updated",
    COMMENT_DELETED:"Comment Deleted",
    ONLY_UPDATED_OWN_POST:"You can only update Your Post",
    ONLY_DELETE_OWN_POST:"You can only delete Your Post",
    NOT_ALLOWED_TO_UNVERIFIED:"Request to Verify Your Account",
    ONLY_VERIFIED_USER_CAN:"Only Verified User can Access"

}